pipeline:
  dryrun:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Dockerfile.multiarch
      dry_run: true
      repo: woodpeckerci/plugin-surge-preview
      platforms: linux/amd64,linux/arm64
      tag: test
    when:
      event: pull_request

  publish-next:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Dockerfile.multiarch
      repo: woodpeckerci/plugin-surge-preview
      platforms: linux/amd64,linux/arm64
      tag: next
    secrets: [docker_username, docker_password]
    when:
      branch: main
      event: push

  publish-tag:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: Dockerfile.multiarch
      repo: woodpeckerci/plugin-surge-preview
      platforms: linux/amd64,linux/arm64
      tag: [latest, "${CI_COMMIT_TAG}"]
    secrets: [docker_username, docker_password]
    when:
      event: tag
